//
// Automatically generated make config: don't edit
// Chameleon Configuration
// Wed Aug  7 21:43:55 2013
// 
#define CONFIG_IS_BUILTIN   1
#define CONFIG_IS_MODULE    2
#define CONFIG_BOOT1_HFS_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS CONFIG_IS_BUILTIN
#define CONFIG_MODULES CONFIG_IS_BUILTIN
#define CONFIG_BOOT0_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_OPTIMIZATION_LEVEL "-Oz"
#define CONFIG_BDMESG CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE CONFIG_IS_BUILTIN
#define CONFIG_FDISK440 CONFIG_IS_BUILTIN
#define CONFIG_KEYLAYOUT_MODULE CONFIG_IS_MODULE
