//
// Automatically generated make config: don't edit
// Chameleon Configuration
// Fri Jul 29 17:57:17 2011
// 
#define CONFIG_IS_BUILTIN   1
#define CONFIG_IS_MODULE    2
#define CONFIG_UCLIBCXX_MODULE CONFIG_IS_MODULE
#define CONFIG_KLIBC_MODULE CONFIG_IS_MODULE
#define CONFIG_BOOT1_HFS_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS CONFIG_IS_BUILTIN
#define CONFIG_MODULES CONFIG_IS_BUILTIN
#define CONFIG_BOOT0_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_OPTIMIZATION_LEVEL "-Oz"
#define CONFIG_BDMESG CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE CONFIG_IS_BUILTIN
#define CONFIG_FDISK440 CONFIG_IS_BUILTIN
#define CONFIG_RESOLUTION_MODULE CONFIG_IS_MODULE
