MODULE_NAME = FileSystem
MODULE_DESCRIPTION = This module provides an api for talking implementing and talking to a filesystem driver.
MODULE_AUTHOR = 
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = uClibcxx BiosDisk

DIR = HelloWorld
SUBDIRS = HFS

MODULE_OBJS = FileSystem.o

include ../MakeInc.dir