MODULE_NAME = ATiGraphicsEnabler
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 

DIR = ATiGraphicsEnabler

MODULE_OBJS = ati.o ATiGraphicsEnabler.o

include ../../MakeInc.dir
