MODULE_NAME = TinyXML
MODULE_DESCRIPTION = This module provides for an api to read XML files.
MODULE_AUTHOR = 
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = uClibcxx

DIR = TinyXML

MODULE_OBJS = tinystr tinyxml tinyxmlerror tinyxmlparser

include ../MakeInc.dir