MODULE_NAME = Memory
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = ---
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = klibc


DIR = Memory

MODULE_OBJS = dram_controllers.o spd.o Memory.o
# mem.o

include ../MakeInc.dir