MODULE_NAME = AMDGraphicsEnabler
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 

DIR = AMDGraphicsEnabler

MODULE_OBJS = ati.o AMDGraphicsEnabler.o

include ../MakeInc.dir
