MODULE_NAME = IntelGraphicsEnabler
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = to be added...
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 

DIR = IntelGraphicsEnabler

MODULE_OBJS = gma.o IntelGraphicsEnabler.o

include ../../MakeInc.dir
