MODULE_NAME = BiosDisk
MODULE_DESCRIPTION = This module provides for an api to interact with the bios to read standard disks.
MODULE_AUTHOR = 
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = uClibcxx

DIR = BiosDisk

MODULE_OBJS = Disk.o BiosDisk.o Main.o

include ../MakeInc.dir