MODULE_NAME = ModuleSystem
MODULE_DESCRIPTION = This provides for support for the module system.
MODULE_AUTHOR = 
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES =

DIR = ModuleSystem

MODULE_OBJS = modules_support.o modules.o

include ../MakeInc.dir