MODULE_NAME = NVIDIAGraphicsEnabler
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = to be added...
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 

DIR = NVIDIAGraphicsEnabler

MODULE_OBJS = nvidia.o NVIDIAGraphicsEnabler.o

include ../MakeInc.dir
