MODULE_NAME = KernelPatcher
MODULE_AUTHOR = Chameleon
MODULE_DESCRIPTION = ---
MODULE_VERSION = "1.0.0"
MODULE_COMPAT_VERSION = "1.0.0"
MODULE_START = $(MODULE_NAME)_start
MODULE_DEPENDENCIES = 


DIR = KernelPatcher

MODULE_OBJS = kernel_patcher.o

include ../MakeInc.dir